'use client';

import { useState, useEffect } from 'react';
import { getApiToken } from '@/utils/auth';
import { format } from 'date-fns';
import { 
  TrendingUp, TrendingDown, Wallet, CreditCard, 
  Smartphone, Banknote, Calendar, Share2 
} from 'lucide-react';
import ReportExportMenu from '@/components/ReportExportMenu';

export default function DailySummaryCard() {
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDailySummary = async () => {
      try {
        const token = await getApiToken();
        const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/summary/daily`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (res.ok) {
          const data = await res.json();
          setSummary(data);
        }
      } catch (err) {
        console.error('Error fetching daily summary:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchDailySummary();
  }, []);

  const shareToWhatsApp = () => {
    if (!summary) return;
    
    const message = `📊 *Daily Summary - ${format(new Date(), 'dd MMM yyyy')}*

💰 *Total Income:* ₹${summary.income.toLocaleString('en-IN')}
💸 *Total Expense:* ₹${summary.expense.toLocaleString('en-IN')}
📈 *Net:* ₹${summary.net.toLocaleString('en-IN')}

*By Payment Mode:*
💵 Cash: ₹${summary.byMode?.cash?.toLocaleString('en-IN') || 0}
📱 UPI: ₹${summary.byMode?.upi?.toLocaleString('en-IN') || 0}
🔖 Credit: ₹${summary.byMode?.credit?.toLocaleString('en-IN') || 0}

_Generated by Desklite_`;

    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  if (loading) {
    return (
      <div className="bg-white rounded-3xl border border-slate-100 shadow-sm p-6">
        <div className="animate-pulse space-y-4">
          <div className="h-6 bg-slate-100 rounded w-1/3"></div>
          <div className="grid grid-cols-3 gap-4">
            <div className="h-16 bg-slate-100 rounded"></div>
            <div className="h-16 bg-slate-100 rounded"></div>
            <div className="h-16 bg-slate-100 rounded"></div>
          </div>
        </div>
      </div>
    );
  }

  if (!summary) return null;

  return (
    <div className="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="px-5 py-4 bg-slate-50/50 border-b border-slate-100 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-slate-900 rounded-xl flex items-center justify-center">
            <Calendar className="w-5 h-5 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900">Today&apos;s Summary</h3>
            <p className="text-xs text-slate-500 font-medium">{format(new Date(), 'EEEE, dd MMMM yyyy')}</p>
          </div>
        </div>
        <button
          onClick={shareToWhatsApp}
          className="p-2.5 bg-green-500 text-white rounded-xl hover:bg-green-600 transition-colors"
          title="Share via WhatsApp"
        >
          <Share2 className="w-4 h-4" />
        </button>
      </div>

      {/* Main Stats */}
      <div className="p-5 grid grid-cols-3 gap-4">
        <div className="text-center">
          <div className="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center mx-auto mb-2">
            <TrendingUp className="w-5 h-5 text-emerald-600" />
          </div>
          <p className="text-lg font-black text-emerald-600">₹{summary.income.toLocaleString('en-IN')}</p>
          <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Income</p>
        </div>
        
        <div className="text-center">
          <div className="w-10 h-10 bg-rose-50 rounded-xl flex items-center justify-center mx-auto mb-2">
            <TrendingDown className="w-5 h-5 text-rose-600" />
          </div>
          <p className="text-lg font-black text-rose-600">₹{summary.expense.toLocaleString('en-IN')}</p>
          <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Expense</p>
        </div>
        
        <div className="text-center">
          <div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center mx-auto mb-2">
            <Wallet className="w-5 h-5 text-blue-600" />
          </div>
          <p className={`text-lg font-black ${summary.net >= 0 ? 'text-blue-600' : 'text-rose-600'}`}>
            ₹{Math.abs(summary.net).toLocaleString('en-IN')}
          </p>
          <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Net</p>
        </div>
      </div>

      {/* Payment Mode Breakdown */}
      <div className="px-5 pb-5">
        <div className="bg-slate-50 rounded-2xl p-4">
          <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">By Payment Mode</p>
          <div className="grid grid-cols-3 gap-3">
            <div className="flex items-center gap-2">
              <Banknote className="w-4 h-4 text-emerald-600" />
              <div>
                <p className="text-sm font-bold text-slate-900">₹{(summary.byMode?.cash || 0).toLocaleString('en-IN')}</p>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Cash</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Smartphone className="w-4 h-4 text-purple-600" />
              <div>
                <p className="text-sm font-bold text-slate-900">₹{(summary.byMode?.upi || 0).toLocaleString('en-IN')}</p>
                <p className="text-[10px] font-bold text-slate-400 uppercase">UPI</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <CreditCard className="w-4 h-4 text-amber-600" />
              <div>
                <p className="text-sm font-bold text-slate-900">₹{(summary.byMode?.credit || 0).toLocaleString('en-IN')}</p>
                <p className="text-[10px] font-bold text-slate-400 uppercase">Credit</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="px-5 pb-5">
        <ReportExportMenu
          payload={{ kind: 'daily', from: new Date().toISOString(), to: new Date().toISOString() }}
          title="Daily Summary"
        />
      </div>

      {/* Transaction Count */}
      <div className="px-5 pb-5">
        <div className="text-center py-2 bg-slate-900 rounded-2xl">
          <p className="text-white font-bold">
            {summary.transactionCount} transactions today
          </p>
        </div>
      </div>
    </div>
  );
}
